export const demoProjects = [
  {
    id: 'ai-code-reviewer',
    title: 'AI Code Reviewer',
    description: 'An AI-powered code review assistant that helps developers write better code by providing real-time suggestions and best practices.',
    demo: 'https://ai-code-reviewer.demo',
    github: 'https://github.com/demo/ai-code-reviewer',
    tags: ['AI', 'Developer Tools', 'Productivity'],
    stars: 0,
    comments: [],
    voters: new Set(),
    status: 'upcoming',
    launchDate: '2024-04-15',
    subscribers: new Set(),
  },
  {
    id: 'design-system-builder',
    title: 'Design System Builder',
    description: 'Create and manage design systems with an intuitive interface. Export to various frameworks and keep your design tokens in sync.',
    demo: 'https://design-system-builder.demo',
    github: 'https://github.com/demo/design-system-builder',
    tags: ['Design', 'Developer Tools', 'Productivity'],
    stars: 0,
    comments: [],
    voters: new Set(),
    status: 'upcoming',
    launchDate: '2024-04-20',
    subscribers: new Set(),
  },
  {
    id: 'retail-connect',
    title: 'Retail Connect',
    description: 'Generate wholesale leads, reach retailers, grow sales. Connect with retailers globally and expand your wholesale reach.',
    demo: 'https://retail-connect.demo',
    github: 'https://github.com/demo/retail-connect',
    tags: ['Sales', 'Marketing', 'E-Commerce'],
    stars: 159,
    comments: [],
    voters: new Set(['user-2', 'user-3']),
    status: 'published',
  },
  {
    id: 'loomos',
    title: 'Loomos',
    description: 'Convert rough Loom recordings to professional videos. AI-powered video enhancement and editing.',
    demo: 'https://loomos.demo',
    github: 'https://github.com/demo/loomos',
    tags: ['Marketing', 'AI', 'Video'],
    stars: 140,
    comments: [],
    voters: new Set(['user-1']),
    status: 'published',
  },
];